version: '3'

services:
  web:
    image: ${WEB_IMAGE:-http-server}
    build:
      context: http-server
    ports:
      - "8080:8080"
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: example
